### ISSUE TITLE
Expose add-on e10s status in add-ons manager

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addon-compatibility-reporter#28]
Let's show e10s status in the add-ons manager, maybe something like (but less ugly than):
![screen shot 2016-07-21 at 19 13 14](https://cloud.githubusercontent.com/assets/873258/17032001/4fadf090-4f77-11e6-953e-2d5415875bd2.png)

@maritz Do we have a nice little e10s icon?

**Comment by maritz** [comment]
@designakt It happened again! :-P
Maybe you should add -designakt to your IRC handle or something, I'm not sure.

**Comment by wagnerand** [comment]
@maritz Oops, so sorry!

**Comment by maritz** [comment]
No worries. Actually this highlights a problem with @ mentions on github: You have no immediate visual feedback on who you're actually mentioning (without clicking on the link). And the auto-complete does not help in this case either, not even offering Markus or designakt as an option.

Since this has nothing to do with your issues, feel free to delete my comments as soon as Markus has arrived. :-)

**Comment by designakt** [comment]
Having 2 handles is a pain. I will solve this one time.

**Comment by designakt** [comment]
@wagnerand Why would you like to e10s status?
And why would you like to mark the ones that are compatible? So far we only show an indication if something is wrong with an add-on. Following that logic we would need to mark the ones that are not compatible. (As we did with signing.)

**Comment by designakt** [comment]
Oh, that is not intended to ship with Firefox, 
but be part of an add-on. In that case:
Sorry, I am not aware of any e10s icon.

**Comment by wagnerand** [comment]
We want to give technical users the ability to identify e10s incompatible add-ons. As we already plan to report e10s status as part of the ACR reports, it makes sense to combine the efforts.

Thanks, I guess I'll come up with something then.
