### ISSUE TITLE
not working with latest update of Firefox 56

### ISSUE THREAD

**Issue by helkav** [mozilla/addon-compatibility-reporter#92]
report issue button not displaying

**# about:buildconfig**
~~~~~~~~~~~~~~~~
Source

Built from https://hg.mozilla.org/releases/mozilla-release/rev/3e4ce49f3214e87a52a2b70ca7fbdffe20bef362
Build platform
target
x86_64-pc-mingw32
Build tools
Compiler 	Version 	Compiler flags
z:/build/build/src/vs2015u3/VC/bin/amd64/cl.exe 	19.00.24213 	-TC -nologo -wd4091 -D_HAS_EXCEPTIONS=0 -W3 -Gy -Zc:inline -Gw -wd4244 -wd4267 -we4553
z:/build/build/src/vs2015u3/VC/bin/amd64/cl.exe 	19.00.24213 	-utf-8 -TP -nologo -wd5026 -wd5027 -Zc:sizedDealloc- -wd4091 -wd4577 -D_HAS_EXCEPTIONS=0 -W3 -Gy -Zc:inline -Gw -wd4251 -wd4244 -wd4267 -wd4800 -wd4595 -we4553 -GR- -Zi -GL -wd4624 -wd4952 -O1 -Oi -Oy
Configure options

MOZ_AUTOMATION=1 'MOZILLABUILD=C:\mozilla-build' --host=x86_64-pc-mingw32 --target=x86_64-pc-mingw32 --enable-update-channel=release MOZILLA_OFFICIAL=1 MOZ_PGO=1 WINDOWSSDKDIR=z:/build/build/src/vs2015u3/SDK MAKECAB=z:/build/build/src/makecab.exe --enable-jemalloc --enable-js-shell RUSTC=z:/build/build/src/rustc/bin/rustc CARGO=z:/build/build/src/rustc/bin/cargo --with-mozilla-api-keyfile=c:/builds/mozilla-desktop-geoloc-api.key --with-google-api-keyfile=c:/builds/gapi.data LLVM_CONFIG=z:/build/build/src/clang/bin/llvm-config --enable-rust-simd MAKE=z:/build/build/src/mozmake.EXE --enable-crashreporter --enable-official-branding --enable-verify-mar

**Comment by wagnerand** [comment]
Thank you for the report!

I am not sure how mozilla repository and building information is relevant here, the add-on is not part of that repository.

**Comment by helkav** [comment]
I just copied and pasted everything form about:buildconfig so you had all the information you need - some may be unnecessary

**Comment by wagnerand** [comment]
Ah ok.

Without more information about the exact issue it's hard to pinpoint what's going on.

Aside from that, this add-on will stop working in just a few weeks and we don't plan on making it compatible with the new Firefox version, since it won't be needed anymore.

Thank you.

**Comment by helkav** [comment]
yeah fair enough - it's just not worth it for addon developers anymore is it? I believe FF has shot itself in (whatever appendage is a foot for a browser) with this accross the board webextensions implementation making most of my fave plugins /addons incompatible. I don't want to but think I will have to move. btw thanks for a great addon - has served well up until now

**Comment by wagnerand** [comment]
If you don’t mind me asking, which add-ons are you using that you are expecting to stop working?

**Comment by helkav** [comment]
some of my faves : sessionmanager, showprofile, tab groups, noscript
most important are noscript and showprofile as I can't find good substitutes at the moment
I'm gradually moving my stuff in the session manager and tab groups to bookmarks and pocket (FF seems to want me to use this so, ok...)
I use multiple profiles ( approx 10) so this is a slow, gradual process!
even firebug displays as a legacy webextension!
I know I'm not the only one unhappy about this : 
https://blog.mozilla.org/addons/2017/09/28/webextensions-in-firefox-57/
hard to know exactly how many users are peed off though as Firefox haven't exactly polled people if they are happy with their addons not being useable from 57!

I am also currently trying palemoon alongside FF and am liking it so far...noscript works but unfortunately not showprofile - I can live with that

**Comment by wagnerand** [comment]
Thank you for getting back to us, I will try my best to help you.

NoScript is currently being worked on and we expect a working version around the release of Firefox Quantum.
For SessionManager, please try https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/
For Tab groups, please have a look at https://addons.mozilla.org/firefox/addon/tab-center-redux/ and see if it suits you. It might not be a perfect replacement, but we are currently actively working on a feature for add-on developers to bring back the ability to create tab grouping add-ons, so please stay tuned for that.
I don't have a suggestion for Show Profile since it's really old. There might be alternatives out there which I don't know about.

If you need more information about the whole process, please have a look at https://support.mozilla.org/en-US/kb/frequently-asked-questions-firefox-addon

https://docs.google.com/spreadsheets/d/1ZzheVRDnEpAwdQ3eHDVI6Hu5om5zhp2YtSCeB0mmLUQ/edit#gid=0 offers replacements for add-ons that will likely stop working. You can also use https://mozilla.github.io/extension-finder/ to find a replacement.

IF you can't find what you are looking for, please reach out in our forums: https://discourse.mozilla.org/t/favorite-webextensions/17087

Thanks again!

**Comment by helkav** [comment]
thanks for all that - I hadn't seen some of the info in your links - I don't really have time to delve deeply into analysing whether the webextensions upgrade will be good in the long run, just it is kind of leaving people in the lurch in the meantime isn't it?
but, again, thanks for your info - I will try to understand more deeply before sounding off - as they say "a little knowledge is a dangerous thing"

**Comment by wagnerand** [comment]
We also just released a blog post with more information and guidance how to find replacements or alternatives: https://blog.mozilla.org/addons/2017/10/26/helping-find-compatible-extensions/

Hope that helps!

**Comment by atsay** [comment]
Hi @helkav, Firebug features are now available in Firefox devtools. You can find out more [here](https://getfirebug.com/). There's also [documentation](https://developer.mozilla.org/en-US/docs/Tools/Migrating_from_Firebug) on how to make the switch.

**Comment by wagnerand** [comment]
Ugh yea, I intended to link to the latest Firebug blog post, but forgot. Thank you, @atsay for being observant!

**Comment by helkav** [comment]
thanks again guys - just using it now...I think I had a bit already as I use FF dev edition for, well, dev : so I kind of had made the switch without realising! but good links - I was seriously under-using it!
